name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ensure the correct Node.js version

      - name: Install dependencies
        run: npm install  # Installs ESLint and other dependencies

      - name: Run ESLint
        run: npm run lint  # Executes linting
